---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-8.4
  - name: debian-7.8
  - name: centos-7.2
  - name: centos-6.7
  - name: fedora-21
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[terraform::default]
