---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.10
  - name: debian-7.8
  - name: centos-7.1
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[terraform::default]
