---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.10
  - name: ubuntu-16.04
  - name: debian-8.6
  - name: centos-7.2
  - name: centos-6.7
  - name: fedora-25
  - name: windows-2012r2
    driver_config:
      box: WindowsServ2012R2

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[terraform::default]
  - name: gpgme
    run_list:
      - recipe[minitest-handler]
      - recipe[terraform::gpgme]
