<%
test_platforms = %w[
  ubuntu-16.04 ubuntu-18.04 debian-8.10 centos-7.4 centos-6.9 fedora-27
]
chef_versions = %w[13 14]
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
<% test_platforms.each do |plat_ver| %>
  - name: <%= plat_ver %>
    driver:
      box_url: https://app.vagrantup.com/bento/<%= plat_ver %>
<% end %>

verifier:
  name: inspec
  inspec_tests:
    - test/integration/inspec

suites:
<% chef_versions.each do |version| %>
  - name: default-chef<%= version %>
    provisioner:
      product_name: chef
      product_version: <%= version %>
      install_strategy: once
    run_list:
      - recipe[terraform_test::ubuntu]
      - recipe[terraform::default]
<% end %>
